apiVersion: apps/v1
kind: Deployment
metadata:
  name: profiles-deployment
spec:
  template:
    spec:
      containers:
      - name: kfam
        securityContext:
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
