apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-writer
  namespace: kubeflow
spec:
  template:
    spec:
      containers:
      - name: main
        securityContext:
          allowPrivilegeEscalation: false
          seccompProfile:
            type: RuntimeDefault
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 0
          capabilities:
            drop:
            - ALL
      initContainers:
      - image: docker.io/istio/proxyv2:1.22.1
        name: istio-init
        securityContext:
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
          runAsUser: 1337
          runAsNonRoot: true
