apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- kf-istio-resources.yaml
- cluster-roles.yaml
namespace: kubeflow
patches:
- path: patches/seccomp-istio-ingressgateway.yaml
- path: patches/seccomp-istiod.yaml